[template]
raw = [
  ".goreleaser.yml"
]

[[placeholders]]
name = "vendor_name"
type = "string"
prompt = "Vendor name?"
default = "Acme"

[[placeholders]]
name = "capability_id"
type = "string"
prompt = "Capability ID?"
default = "wasmcloud:httpserver"

[[placeholders]]
name = "go_mod_prefix"
type = "string"
prompt = "Go Module name prefix (will add name to end)?"
default = "github.com/wasmcloud"
