[package]
name = "{{ project-name }}"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
async-trait = "0.1"
wasmcloud-interface-factorial = "0.5.0"
wasmbus-rpc = "0.9"

# test dependencies
[dev-dependencies]
wasmcloud-test-util = "0.4.0"
tokio = { version = "1.0", features = [ "full" ] }

[[bin]]
name = "{{to_snake_case project-name}}"
path = "src/main.rs"
