name: Build and test
on:
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "Cargo.*"
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add wasm32-wasi
        run: rustup target add wasm32-wasi
      - name: Check formatting
        run: cargo fmt -- --check
        shell: bash
      - name: Build actor
        run: cargo build
      - name: Check lints with clippy
        run: |
          rustup component add clippy
          cargo clippy
      # Once you've written unit tests for your actor, you can uncomment
      # the two lines below to automatically run tests
      # - name: Test actor
      #   run: cargo test --target x86_64-unknown-linux-gnu -- --nocapture
